### PR TITLE
Kerlin - process encrypted response

### PR DESCRIPTION
**Pull request by kerlin**
Changes to allow a rails SP using devise, omniauth-shibboleth, and rack-saml to authenticate with idp.testshib.org

### CODE REVIEW

**Comment by toyokazu** [comment]
Thank you for your contribution! I am sorry that after I moved to the new development environment, I have not setup the test environment for rack-saml and currently I cannot have time for it. So, it takes for a while to test your code and merge it... If you have to hurry to update rack-saml, please let me know. Though it is not appropriate approach, I'd like to merge your modifications without testing.

**Comment by kerlin** [comment]
I hope to get back to working with this next week. I might have access to
my university shibboleth then. Let me know if you have any suggestions for
updating docs or adding testing, and I will try to help with that also.
Thanks very much for publishing this gem, it's been a great help.

**Comment by kerlin** [comment]
It is working with our university (fau.edu) idp now with no code changes. Had to add the parameters saml_sp: and assertion_consumer_service_uri: to rack-saml.yml with the same values as found in the Metadata, but without the port (:443) number. The idp wouldn't load the Metadata file with port numbers in those urls. Some people may need to also have the authentication requests signed, but I didn't need that so I haven't looked into it.

**Comment by toyokazu** [comment]
Dear kerlin,

Thank you for testing in your environment!
I am sorry that my new environment is not ready for testing yet...
However, I don't want to postpone merging your contribution anymore.
So, this time, I'd like to trust your test result and merge your request now.
When my testing environment is ready and if I find something wrong, I'd like to let you know by submitting issues.
Thank you again for your contribution!

By the way, currently I don't know the detail operation but if you want to join this project, I'd like to add you as a collaborator of this project and a maintainer of rack-saml gem. Or if you want to make this repository to public one(?), I'd like to try to move it to a group repository, e.g. https://github.com/gakunin. Please let me know if you have such a request.

Best Regards,

**Comment by toyokazu** [comment]
I forgot to write about documentation. Since I did not test your code, I may not understand well how to use new functions. If possible, would you also suggest a modification of README.md?

Best

**Pull request merged**
